apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sentclass
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cloudylabs-public/sentiment-classifier:0.3.3
            env:
              # https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object
              - name: TEXT_PATH
                value: "text"
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: sentiment-classifier-trigger
spec:
  filter:
    sourceAndType:
      type: com.twitter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: sentclass
