apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: slack-tweet-notifier
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: slack-publisher
